services:
  - type: web
    name: sbi-mf-faq-backend
    env: docker
    envVars:
      - key: PYTHONPATH
        value: src
      - key: OMP_NUM_THREADS
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: "us-east-1"
    healthCheckPath: /api/v1/health
    autoDeploy: true
